# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    App\Common\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
